//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public System.Guid Id { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public string Content { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> DisplayTime { get; set; }
    }
}
