//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsImage
    {
        public System.Guid Id { get; set; }
        public string Description { get; set; }
        public string Ext { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public string ArticleLink { get; set; }
        public Nullable<bool> Display { get; set; }
    }
}
